version: "3"

services:
  web_customer:
    build: .
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  web_goods:
    build: .
    command: ["python", "manage.py", "runserver", "0.0.0.0:8001"]
    ports:
      - "8001:8001"
    volumes:
      - .:/app

  web_sales:
    build: .
    command: ["python", "manage.py", "runserver", "0.0.0.0:8002"]
    ports:
      - "8002:8002"
    volumes:
      - .:/app








