# Generated by Django 4.2.7 on 2023-11-29 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=20)),
                ('price_per_item', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('count_in_stock', models.IntegerField()),
            ],
        ),
    ]
